### PR TITLE
Add support for filtering by language type

### LINKED ISSUE #4: Feature request: support by-language breakdown
1. currently, only total stats are available via `?category=`
https://tokei.rs/b1/github/org/repo?category=lines

2. this request is to support by-language breakdown via `?language=`
https://tokei.rs/b1/github/org/repo?language=java,scala

to render badge with:
```
Java:N1 Scala:N2
```

### LINKED ISSUE #6: Badges: add filter ?type=Markdown,Rust
Hello, 
The badge does not really work for me. 
Here is what it shows for my repo

Actually, my real LoC is 1k, because what is relevant in my case is the output of `-t=Kotlin`

The rest is not really part of my codebase. 

```
$ tokei
--------------------------------------------------------------------------
 Language       Files        Lines         Code     Comments       Blanks
--------------------------------------------------------------------------
 Batch              1           84           61            0           23
 JSON              27        14287        14287            0            0
 Kotlin            18          957          668           61          228
 Markdown           4          178          178            0            0
 Shell              1          172          128           23           21
 Plain Text        53         2465         2465            0            0
--------------------------------------------------------------------------
 Total            104        18143        17787           84          272
--------------------------------------------------------------------------
```

I would like to have in the badge URL the same option that in the command line

```
$ tokei --help
    -t, --type <types>            Filters output by language type, seperated by a comma. i.e. -t=Rust,Markdown
```

### PR DESCRIPTION
**Pull request by elliotwutingfeng**
Closes #6

Closes #4

You can choose to count lines only for specific language type(s), by using the `?type=` query string. Languages are to be separated by a comma.

For example,

```markdown
https://tokei.rs/b1/github/XAMPPRocky/tokei?type=JSON,Rust,Markdown
```

- Unsupported languages are ignored.
- Leaving `?type=` blank leads to the default behavior of counting lines for all supported languages.

## Live Demo

[lines of json](https://github.com/XAMPPRocky/tokei)

[lines of json and rust](https://github.com/XAMPPRocky/tokei)

[lines of json, rust, and markdown](https://github.com/XAMPPRocky/tokei)

[all lines](https://github.com/XAMPPRocky/tokei)

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Is there a reason you've marked it as a draft?

**Comment by elliotwutingfeng** [comment]
> Thank you for your PR! Is there a reason you've marked it as a draft?

No problem! This PR currently works, however, the caching of results for unique combinations of commit SHA hash and the `?type=` values would lead to multiple `git clone`s for the same SHA hash.

This would get worse if `?exclude=` were to be implemented, which I am interested in working on.

I am thinking of caching results for the SHA hash only, and filtering by language type afterwards (filtering is cheap).

What do you think? Or alternatively I'll make this optimisation in a later PR.

**Comment by XAMPPRocky** [comment]
> I am thinking of caching results for the SHA hash only, and filtering by language type afterwards (filtering is cheap).

I think that's the right approach, reducing cloning is critical since RAM is quite limited on the VPS machine.

**Comment by elliotwutingfeng** [comment]
I've reverted the caching to SHA hash only.

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Pull request merged**
