### PR TITLE
Add primary language badge

### LINKED ISSUE #87: Primary language badge
I think it would be nice to have a badge for the language with the most lines (probably by LoC)? It could look something like this: Primary Language Badge

It would be cool if each language had its own color, but to get the feature started it might be best if all languages used the same color (blue) as the other badges.

### PR DESCRIPTION
**Pull request by spenserblack**
Resolves #87

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Sorry for getting to it so late., and I've made changes to address other issues that change what's required here. Are you still interested in this?

**Comment by spenserblack** [comment]
OK, merge conflicts should be resolved and added badge should now work with new dependencies.

Although when I view in browser it seems like a download is triggered instead of the SVG getting rendered :thinking: 
I don't think this happened in the pre-merge version IIRC
But I suppose that's unrelated to this PR :shrug:

**Comment by spenserblack** [comment]
@XAMPPRocky Are any other changes needed for this PR?

**Comment by XAMPPRocky** [comment]
Nope, looks good to me. Sorry for the delay, but I'll merge and deploy this soon.

**Comment by spenserblack** [comment]
Cleaning up old PRs and forks. Will probably delete the fork soon, but the refs in this PR should still be reachable via `refs/pull/NUMBER/head`.

**Pull request closed without merging**
